

services:
  grist:
    image: gristlabs/grist:1.0.8 # Change! --> https://hub.docker.com/r/gristlabs/grist/tags
    container_name: grist
    env_file:
      - .env
    environment:
      - GRIST_DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - GRIST_DOMAIN=${GRIST_DOMAIN}
      - APP_HOME_URL=https://${GRIST_DOMAIN}
      - GRIST_SINGLE_ORG=${GRIST_SINGLE_ORG}
      - GRIST_HIDE_UI_ELEMENTS=${GRIST_HIDE_UI_ELEMENTS}
      - GRIST_LIST_PUBLIC_SITES=${GRIST_LIST_PUBLIC_SITES}
      - GRIST_MAX_UPLOAD_ATTACHMENT_MB=${GRIST_MAX_UPLOAD_ATTACHMENT_MB}
      - GRIST_MAX_UPLOAD_IMPORT_MB=${GRIST_MAX_UPLOAD_IMPORT_MB}
      - GRIST_ORG_IN_PATH=${GRIST_ORG_IN_PATH}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_HOST=${TYPEORM_HOST}
      - TYPEORM_LOGGING=${TYPEORM_LOGGING}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_TYPE=${TYPEORM_TYPE}
    volumes:
      - grist:/persist
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grist.rule=Host(`${GRIST_DOMAIN}`)"
      - "traefik.http.routers.grist.entrypoints=websecure"
      - "traefik.http.routers.grist.tls.certresolver=letsencrypt"
      - "traefik.http.services.grist.loadbalancer.server.port=3000"
    #ports:
    #  - 3000:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: grist_postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  traefik:
    external: true
  grist:
    driver: bridge

volumes:
  grist:
    driver: local 
  postgres:
    driver: local